name: build

on:
  push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aaa/aaa
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Get first tag
        id: get_tag
        run: echo "$(echo ${{ steps.meta.outputs.tags }} | cut -d $'\n' -f 1)"

